name: hkcw_engine2
description: Flutter plugin for WebView2 desktop wallpaper engine
version: 1.0.0
homepage: https://github.com/yourusername/hkcw_engine2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: HkcwEngine2Plugin
        fileName: hkcw_engine2_plugin.cpp
  
  assets:
    - windows/hkcw_sdk.js

